### PR TITLE
Split `RouteCommand` and `RouteEvent()` methods into separate methods.

### PR DESCRIPTION
**Pull request by jmalloc**
This is a real quick mock-up of one approach we could take to split the "probing" functionality out of the `RouteCommand()` and `RouteEvent()` methods, as we started to discuss in #30.

### CODE REVIEW

**Comment by jmalloc** [comment]
I'm not looking to merge this immediately. I'll have a bit more of a play around with the in-memory engine implementation to see how it feels first.

**Comment by jmalloc** [comment]
The bank example in #28 is now based off this branch, so you could see what it would look like to use.

**Comment by danilvpetrov** [comment]
While `Configurer` sounds a bit unusual I guess that's what it does at the end of the day. IMHO, any configuration-related term would do in this place be that  `Configurer`, `Settings`, `Config`, etc. 

I wonder though would it be any beneficial to make methods `RouteCommandType()` and `RouteEventType()` variadic?

**Comment by jmalloc** [comment]
> I wonder though would it be any beneficial to make methods `RouteCommandType()` and `RouteEventType()` variadic?

I had considered this, but this kind of thing has bitten me in the past when I've needed to expand the function signature.  For example, if we want to accept additional parameters/options about each message in the future.

**Comment by danilvpetrov** [comment]
Ah, that makes perfect sense. It's looking good to me, but like @koden-km mentioned, I better hold off for a little in case there are more changes coming.

**Comment by jmalloc** [comment]
I'm going to merge this for now to move on with some other changes that I want to do so that I can continue with some engine prototyping.  I fully expect it will need further revision, though.

**Pull request merged**
