### PR TITLE
Add command handler and event handler.

### LINKED ISSUE #35: Integration handlers, and the split between domain and integration messages.
We've had a few chats now about the "integration handler", and what kind of messages it can accept.  While trying to probe out what we need I came up with a little matrix of which handlers can send/receive which "classes" of messages. 

Remember that there is still only one `Message` interface, so this is largely conceptual -- but it could perhaps be enforced by certain engine implementations.

In the matrix below, I'm experimenting with the idea of splitting the `IntegrationMessageHandler` concept into separate `CommandHandler` and `EventHandler` interfaces.

The columns are the various types of message consumers/producers. "External" refers to any mechanism that could be used to send messages to a Dogma application from the outside. The rows are the various categories of messages.

|                        | Aggregate | Process     | ~Command Handler~ Integration | ~Event Handler~ Projection | ~External~ Sender #40  |
|------------------------|:---------:|:-----------:|:---------------:|:-------------:|:--------:|
| **Domain Command**     | recv      | send        |                 |               | send     |
| **Domain Event**       | send      | recv        |                 | recv          |          |
| **Non-Domain Command** |           | send        | recv            |               |          |
| **Non-Domain Event**   |           | recv        | send            | ~recv (?)~      | send     |
| **Timeout**            |           | send & recv |                 |               |          |

### LINKED ISSUE #40: Consider including a "sender" interface.
This would be the in-code representation of the "external" column in "the matrix" described in #35.

We would need to include such an interface in order to make integrations portable across multiple engines.

### PR DESCRIPTION
**Pull request by jmalloc**
Fixes #35, Fixes #40

Ok, so here are the "integration" handlers, which is a word I am increasingly less fond of using. Event handlers specifically are not only for integration events, they will also very commonly handle domain events, such as when building a read model.

As mentioned in Slack, I'm also not super fond of the `[Command|Event]HandlerConfigurer` names, but I can't think of anything better so far... for consistency, should `AggregateConfigurer` be renamed to `AggregateMessageHandlerConfigurer`.  These names are getting awfully long and un-Go-like.

### CODE REVIEW

**Comment by jmalloc** [comment]
Another thing I'm not sure about is whether we should allow a single type to implement multiple of our interfaces.  This is not possible with our current naming scheme, because every handler interface has a `Configure` method with a different signature.

**Comment by jmalloc** [comment]
I've also added the "sender" interfaces as proposed in #40, so this PR would now be considered to offer a "complete" Dogma API.  Overall, the documentation still needs a lot of work.

**Comment by koden-km** [comment]
I'm not sure if there would be any type that should implement more than one of the interfaces. If something did, then it would not be following single responsibility? Also, it would have too much power to make it easy to write bad code?

**Comment by jmalloc** [comment]
> I'm not sure if there would be any type that should implement more than one of the interfaces. If something did, then it would not be following single responsibility? Also, it would have too much power to make it easy to write bad code?

I think with the current naming it makes sense that any given type can only implement one of the interfaces. 

As with the other PRs, I'm going to merge this as is and keep pushing towards v1 feature completeness, and then have yet another naming review once everything is present.

**Comment by danilvpetrov** [comment]
Sorry guys, finally had a chance to read this PR and your comments. Everything makes sense to me here. Since @jmalloc  said we will have another naming review, we can probably decide whether it's appropriate to let a single type implement all the mentioned interfaces. However, I am with @koden-km  on this issue: we should probably not allow users to write a type that would implement two these interfaces at the same time.

**Pull request merged**
